/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRecruitmentRouteImport } from './routes/_app.recruitment'
import { Route as AppJobsRouteImport } from './routes/_app.jobs'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCandidatesRouteImport } from './routes/_app.candidates'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecruitmentRoute = AppRecruitmentRouteImport.update({
  id: '/recruitment',
  path: '/recruitment',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesRoute = AppCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidates': typeof AppCandidatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/jobs': typeof AppJobsRoute
  '/recruitment': typeof AppRecruitmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidates': typeof AppCandidatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/jobs': typeof AppJobsRoute
  '/recruitment': typeof AppRecruitmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/candidates': typeof AppCandidatesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/recruitment': typeof AppRecruitmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/candidates' | '/dashboard' | '/jobs' | '/recruitment'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/candidates' | '/dashboard' | '/jobs' | '/recruitment'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/candidates'
    | '/_app/dashboard'
    | '/_app/jobs'
    | '/_app/recruitment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/recruitment': {
      id: '/_app/recruitment'
      path: '/recruitment'
      fullPath: '/recruitment'
      preLoaderRoute: typeof AppRecruitmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates': {
      id: '/_app/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AppCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCandidatesRoute: typeof AppCandidatesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppJobsRoute: typeof AppJobsRoute
  AppRecruitmentRoute: typeof AppRecruitmentRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCandidatesRoute: AppCandidatesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppJobsRoute: AppJobsRoute,
  AppRecruitmentRoute: AppRecruitmentRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
